# Generated by Django 5.0.4 on 2024-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TE', 'تکنولوژیُ'), ('VG', 'بازی های ویدئویی')], default='TE', max_length=2),
        ),
    ]
