# Generated by Django 5.0.4 on 2024-04-22 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, null=django.utils.timezone.now, unique_for_date='publish'),
            preserve_default=django.utils.timezone.now,
        ),
    ]
