# Generated by Django 5.0.2 on 2024-03-08 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid registration first_name in the format a-z A-Z', regex='^[a-zA-Z]$')])),
                ('last_name', models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid last_name in the format a-z A-Z', regex='^[a-zA-Z]$')])),
                ('phone_number', models.CharField(default=0, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid registration phone number in the format 09XXXXXXXXX', regex='^[0-9]$')])),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('postal_code', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Enter a valid  postal code with numbers between 0-9', regex='^[0-9]$')])),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('recipient_first_name', models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid  first_name in the format a-z A-Z', regex='^[a-zA-Z]$')])),
                ('recipiemt_last_name', models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid  last_name in the format a-z A-Z', regex='^[a-zA-Z]$')])),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('postal_code', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Enter a valid  postal code with numbers between 0-9', regex='^[0-9]$')])),
                ('building_number', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Enter a valid  building_number with numbers between 0-9', regex='^[0-9]$')])),
                ('building_unit_number', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Enter a valid building_unit_number with numbers between 0-9', regex='^[0-9]$')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
