# Generated by Django 5.0.2 on 2024-03-08 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_address_profile_address_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid  building_number with numbers between 0-9', regex='^[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_unit_number',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid building_unit_number with numbers between 0-9', regex='^[0-9]$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid  postal code with numbers between 0-9', regex='^[0-9]$')]),
        ),
    ]
