# Generated by Django 5.0.2 on 2024-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_address_building_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
