# Generated by Django 5.0.2 on 2024-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_address_building_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='recipiemt_last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='recipient_first_name',
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_full_name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
