# Generated by Django 5.0.2 on 2024-04-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_profile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
